name: apphjarnfokus
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.2
  firebase_storage: ^10.2.11
  firebase_auth: ^3.3.13
  cloud_firestore: ^3.1.11
  audioplayers: ^0.20.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  get:
  get_storage:
  syncfusion_flutter_pdfviewer: ^19.4.56-beta
  provider: ^6.0.3
  flutter_alarm_clock: ^0.0.2
  youtube_player_flutter: ^8.0.0
  url_launcher: ^6.1.3
  dropdown_button2: ^1.4.0
  flutter_switch: ^0.3.2
#  awesome_notifications: ^0.6.21
#  android_alarm_manager_plus: ^2.0.6
  flutter_local_notifications: ^9.4.0
  rxdart: ^0.27.4
  timezone: ^0.8.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.3+1
  hive_generator: ^1.1.2
  build_runner: ^2.1.10

flutter_native_splash:
  image: images/logo2x.png
  color: "#3eafc1"


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/intro0.png
    - images/intro1.png
    - images/intro2.png
    - images/intro0@2x.png
    - images/intro1@2x.png
    - images/intro2@2x.png
    - images/man.jpeg
    - images/next.png
    - images/previous.png
    - images/logo.png
    - images/logo2x.png
    - images/logo320x480.png
    - images/play.png
    - images/PARK.png
    - images/practice-play-img.png
    - images/back15.png
    - images/forward15.png
    - images/list-practice-icon.png
    - images/pause.png
    - images/Mjukstarta dagen.png
    - images/Fokusminuten.png
    - images/Gå med fokus.png
    - images/Andrum.png
    - images/Introduktion.png
    - images/Powerpausen.png
    - images/Skarpt fokus.png
    - images/Somna.png
    - images/Stå stadigt.png
    - images/Tre medvetna andetag.png
    - images/Öppet fokus.png
    - images/about.png
    - images/logo_purchase.png
    - images/a.png
    - assets/Hjarnfokus_Johan_Bergstaf.pdf
    - assets/assets_note1.wav
  fonts:
    - family: black
      fonts:
        - asset: fonts/Roboto-Black.ttf
    - family: light
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: medium
      fonts:
        - asset: fonts/Roboto-Medium.ttf